-- Controlled-vocabulary + dimension + operational tables (db-design.md §2).

CREATE TABLE pollutant (
    code             TEXT PRIMARY KEY,            -- PM2.5, PM10, NO2, SO2, CO, O3, NH3, Pb
    display_name     TEXT NOT NULL,
    unit             TEXT NOT NULL,               -- CPCB convention: CO=mg/m3, others ug/m3
    zero_implausible BOOLEAN NOT NULL DEFAULT FALSE,
    range_min        DOUBLE PRECISION,
    range_max        DOUBLE PRECISION
);

CREATE TABLE station (
    id            TEXT PRIMARY KEY,               -- IN-<STATE>-<seq4>, e.g. IN-DL-0042
    name          TEXT NOT NULL,
    name_norm     TEXT NOT NULL,                  -- normalized for fuzzy alias matching
    city          TEXT,
    state         TEXT,
    state_code    TEXT,
    agency        TEXT,
    station_type  TEXT NOT NULL DEFAULT 'UNKNOWN',-- CAAQMS | MANUAL | UNKNOWN
    geom          geometry(Point, 4326),
    status        TEXT NOT NULL DEFAULT 'UNKNOWN',-- ACTIVE | INACTIVE | UNKNOWN
    needs_review  BOOLEAN NOT NULL DEFAULT FALSE,
    first_seen    TIMESTAMPTZ,
    last_seen     TIMESTAMPTZ
);
CREATE INDEX idx_station_geom ON station USING GIST (geom);
CREATE INDEX idx_station_city ON station (city);
CREATE INDEX idx_station_state ON station (state_code);

CREATE TABLE station_alias (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source           TEXT NOT NULL,
    source_key       TEXT NOT NULL,
    station_id       TEXT NOT NULL REFERENCES station(id),
    source_name_raw  TEXT,
    match_method     TEXT NOT NULL DEFAULT 'AUTO',  -- EXACT | FUZZY | OVERRIDE | AUTO
    match_confidence DOUBLE PRECISION,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source, source_key)
);

CREATE TABLE ingestion_run (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source        TEXT NOT NULL,
    window_start  TIMESTAMPTZ,
    window_end    TIMESTAMPTZ,
    started_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at   TIMESTAMPTZ,
    outcome       TEXT,                            -- SUCCESS | PARTIAL | FAILED
    fetched       INTEGER NOT NULL DEFAULT 0,
    inserted      INTEGER NOT NULL DEFAULT 0,
    updated       INTEGER NOT NULL DEFAULT 0,
    duplicate     INTEGER NOT NULL DEFAULT 0,
    rejected      INTEGER NOT NULL DEFAULT 0,
    error_detail  TEXT,
    raw_ref       TEXT,
    reject_samples JSONB
);
CREATE INDEX idx_run_source_started ON ingestion_run (source, started_at DESC);

CREATE TABLE api_client (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_hash            TEXT NOT NULL UNIQUE,       -- SHA-256 hex of the raw key
    email               TEXT,
    tier                TEXT NOT NULL DEFAULT 'KEYED', -- ANONYMOUS | KEYED | PARTNER
    rate_limit_override INTEGER,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked             BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE qc_config (
    ruleset_version TEXT NOT NULL,
    key             TEXT NOT NULL,
    value           TEXT NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ruleset_version, key)
);
CREATE INDEX idx_qc_config_active ON qc_config (active);

CREATE TABLE aqi_breakpoint (
    pollutant       TEXT NOT NULL REFERENCES pollutant(code),
    band_low_index  INTEGER NOT NULL,
    band_high_index INTEGER NOT NULL,
    conc_low        DOUBLE PRECISION NOT NULL,
    conc_high       DOUBLE PRECISION NOT NULL,
    avg_hours       INTEGER NOT NULL,              -- 24 for most, 8 for CO/O3
    PRIMARY KEY (pollutant, band_low_index)
);

-- ShedLock distributed scheduler lock (FR-1.6).
CREATE TABLE shedlock (
    name       TEXT PRIMARY KEY,
    lock_until TIMESTAMPTZ NOT NULL,
    locked_at  TIMESTAMPTZ NOT NULL,
    locked_by  TEXT NOT NULL
);
