-- City-level daily AQI history layer (db-design.md §2). Kept separate from measurement.

CREATE TABLE city_daily_aqi (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city                TEXT NOT NULL,
    state               TEXT,
    aqi_date            DATE NOT NULL,
    aqi                 INTEGER,
    prominent_pollutant TEXT,
    source              TEXT NOT NULL,             -- e.g. urbanemissions, cpcb-bulletin
    raw_ref             TEXT,
    qc_flags            INTEGER NOT NULL DEFAULT 0,
    ingested_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (city, aqi_date, source)
);
CREATE INDEX idx_city_daily_aqi_city_date ON city_daily_aqi (city, aqi_date DESC);
